<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Application">
    <TargetFramework>netstandard2.0</TargetFramework>
    <Product>LinqToDB.AspNet Extensions</Product>
    <VersionPart1>5</VersionPart1>
    <VersionPart2>4</VersionPart2>
  </PropertyGroup> 
  <ItemGroup Label="PackageReferences">
    <PackageReference Include="linq2db.AspNet" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions"  />
  </ItemGroup> 
  <ItemGroup>
    <ProjectReference Include="..\.DataProvider\xLinqToDB.DataProvider.csproj" />
  </ItemGroup>
</Project>