<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Application">
    <TargetFramework>net10.0</TargetFramework>
    <Product>Microsoft.EntityFrameworkCore DB2iSeries Extensions Tests</Product>
    <IsPackable>false</IsPackable>
    <VersionPart1>10</VersionPart1>
  </PropertyGroup>
  <ItemGroup Label="PackageReferences">
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xUnit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Moq" />
  </ItemGroup>
  <ItemGroup Label="ProjectReferences">
    <ProjectReference Include="..\xMicrosoft.EntityFrameworkCore.DB2iSeries.csproj" />
  </ItemGroup>
</Project>