<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Application">
    <Product>Common DotNet Extensions</Product>
    <RootNamespace>Common</RootNamespace>
    <VersionPart1>8</VersionPart1>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\x\xSystem\.DotNet\xSystem.DotNet.csproj" />
    <ProjectReference Include="..\.DotNetStandard\Common.DotNetStandard.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Structures\_DateTime\Integers\" />
  </ItemGroup>
</Project>