<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Application">
    <!--
    <TargetFramework>netstandard2.0</TargetFramework>
    <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
    -->
    <Product>Microsoft.AspNetCore Extensions</Product>
    <VersionPart1>8</VersionPart1>
  </PropertyGroup>
  <ItemGroup Label="FrameworkReferences">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup Label="ProjectReferences">
    <ProjectReference Include="..\..\..\Common\.DotNetStandard\Common.DotNetStandard.csproj" />
    <ProjectReference Include="..\.Extensions\xMicrosoft.Extensions.csproj" />
    <ProjectReference Include=".Http\xMicrosoft.AspNetCore.Http.csproj" />
    <!--
    <ProjectReference Include="$(RepoSrcDir_X10sions)x\xMicrosoft\.Extensions\xMicrosoft.Extensions.csproj" />
    -->
  </ItemGroup>
</Project>