using System.ComponentModel;

namespace Common.Enums {

  /// <summary>
  /// https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes
  /// </summary>
  public enum LanguageIsoCode639 {
    [Description("Abkhazian")] AB,
    [Description("Afar")] AA,
    [Description("Afrikaans")] AF,
    [Description("Akan")] AK,
    [Description("Albanian")] SQ,
    [Description("Amharic")] AM,
    [Description("Arabic")] AR,
    [Description("Aragonese")] AN,
    [Description("Armenian")] HY,
    [Description("Assamese")] AS,
    [Description("Avaric")] AV,
    [Description("Avestan")] AE,
    [Description("Aymara")] AY,
    [Description("Azerbaijani")] AZ,
    [Description("Bambara")] BM,
    [Description("Bashkir")] BA,
    [Description("Basque")] EU,
    [Description("Belarusian")] BE,
    [Description("Bengali (Bangla)")] BN,
    [Description("Bihari")] BH,
    [Description("Bislama")] BI,
    [Description("Bosnian")] BS,
    [Description("Breton")] BR,
    [Description("Bulgarian")] BG,
    [Description("Burmese")] MY,
    [Description("Catalan")] CA,
    [Description("Chamorro")] CH,
    [Description("Chechen")] CE,
    [Description("Chichewa, Chewa, Nyanja")] NY,
    [Description("Chinese")] ZH,
    //[Description("Chinese (Simplified)")] ZH-HANS,
    //[Description("Chinese (Traditional)")] ZH-HANT,
    [Description("Chuvash")] CV,
    [Description("Cornish")] KW,
    [Description("Corsican")] CO,
    [Description("Cree")] CR,
    [Description("Croatian")] HR,
    [Description("Czech")] CS,
    [Description("Danish")] DA,
    [Description("Divehi, Dhivehi, Maldivian")] DV,
    [Description("Dutch")] NL,
    [Description("Dzongkha")] DZ,
    [Description("English")] EN,
    [Description("Esperanto")] EO,
    [Description("Estonian")] ET,
    [Description("Ewe")] EE,
    [Description("Faroese")] FO,
    [Description("Fijian")] FJ,
    [Description("Finnish")] FI,
    [Description("French")] FR,
    [Description("Fula, Fulah, Pulaar, Pular")] FF,
    [Description("Galician")] GL,
    [Description("Gaelic (Scottish)")] GD,
    [Description("Georgian")] KA,
    [Description("German")] DE,
    [Description("Greek")] EL,
    [Description("Guarani")] GN,
    [Description("Gujarati")] GU,
    [Description("Haitian Creole")] HT,
    [Description("Hausa")] HA,
    [Description("Hebrew")] HE,
    [Description("Herero")] HZ,
    [Description("Hindi")] HI,
    [Description("Hiri Motu")] HO,
    [Description("Hungarian")] HU,
    [Description("Icelandic")] IS,
    [Description("Ido")] IO,
    [Description("Igbo")] IG,
    [Description("Indonesian")] ID, IN,
    [Description("Interlingua")] IA,
    [Description("Interlingue")] IE,
    [Description("Inuktitut")] IU,
    [Description("Inupiak")] IK,
    [Description("Irish")] GA,
    [Description("Italian")] IT,
    [Description("Japanese")] JA,
    [Description("Javanese")] JV,
    [Description("Kalaallisut, Greenlandic")] KL,
    [Description("Kannada")] KN,
    [Description("Kanuri")] KR,
    [Description("Kashmiri")] KS,
    [Description("Kazakh")] KK,
    [Description("Khmer")] KM,
    [Description("Kikuyu")] KI,
    [Description("Kinyarwanda (Rwanda)")] RW,
    [Description("Kirundi")] RN,
    [Description("Kyrgyz")] KY,
    [Description("Komi")] KV,
    [Description("Kongo")] KG,
    [Description("Korean")] KO,
    [Description("Kurdish")] KU,
    [Description("Kwanyama")] KJ,
    [Description("Lao")] LO,
    [Description("Latin")] LA,
    [Description("Latvian (Lettish)")] LV,
    [Description("Limburgish ( Limburger)")] LI,
    [Description("Lingala")] LN,
    [Description("Lithuanian")] LT,
    [Description("Luga-Katanga")] LU,
    [Description("Luganda, Ganda")] LG,
    [Description("Luxembourgish")] LB,
    [Description("Manx, Gaelic")] GV,
    [Description("Macedonian")] MK,
    [Description("Malagasy")] MG,
    [Description("Malay")] MS,
    [Description("Malayalam")] ML,
    [Description("Maltese")] MT,
    [Description("Maori")] MI,
    [Description("Marathi")] MR,
    [Description("Marshallese")] MH,
    [Description("Moldavian")] MO,
    [Description("Mongolian")] MN,
    [Description("Nauru")] NA,
    [Description("Navajo")] NV,
    [Description("Ndonga")] NG,
    [Description("Northern Ndebele")] ND,
    [Description("Nepali")] NE,
    [Description("Norwegian")] NO,
    [Description("Norwegian bokmål")] NB,
    [Description("Norwegian nynorsk")] NN,
    [Description("Occitan")] OC,
    [Description("Ojibwe")] OJ,
    [Description("Old Church Slavonic, Old Bulgarian")] CU,
    [Description("Oriya")] OR,
    [Description("Oromo (Afaan Oromo)")] OM,
    [Description("Ossetian")] OS,
    [Description("Pāli")] PI,
    [Description("Pashto, Pushto")] PS,
    [Description("Persian (Farsi)")] FA,
    [Description("Polish")] PL,
    [Description("Portuguese")] PT,
    [Description("Punjabi (Eastern)")] PA,
    [Description("Quechua")] QU,
    [Description("Romansh")] RM,
    [Description("Romanian")] RO,
    [Description("Russian")] RU,
    [Description("Sami")] SE,
    [Description("Samoan")] SM,
    [Description("Sango")] SG,
    [Description("Sanskrit")] SA,
    [Description("Serbian")] SR,
    [Description("Serbo-Croatian")] SH,
    [Description("Sesotho")] ST,
    [Description("Setswana")] TN,
    [Description("Shona")] SN,
    [Description("Nuosu, Sichuan Yi")] II,
    [Description("Sindhi")] SD,
    [Description("Sinhalese")] SI,
    [Description("Siswati, Swati")] SS,
    [Description("Slovak")] SK,
    [Description("Slovenian")] SL,
    [Description("Somali")] SO,
    [Description("Southern Ndebele")] NR,
    [Description("Spanish")] ES,
    [Description("Sundanese")] SU,
    [Description("Swahili (Kiswahili)")] SW,
    [Description("Swedish")] SV,
    [Description("Tagalog")] TL,
    [Description("Tahitian")] TY,
    [Description("Tajik")] TG,
    [Description("Tamil")] TA,
    [Description("Tatar")] TT,
    [Description("Telugu")] TE,
    [Description("Thai")] TH,
    [Description("Tibetan")] BO,
    [Description("Tigrinya")] TI,
    [Description("Tonga")] TO,
    [Description("Tsonga")] TS,
    [Description("Turkish")] TR,
    [Description("Turkmen")] TK,
    [Description("Twi")] TW,
    [Description("Uyghur")] UG,
    [Description("Ukrainian")] UK,
    [Description("Urdu")] UR,
    [Description("Uzbek")] UZ,
    [Description("Venda")] VE,
    [Description("Vietnamese")] VI,
    [Description("Volapük")] VO,
    [Description("Wallon")] WA,
    [Description("Welsh")] CY,
    [Description("Wolof")] WO,
    [Description("Western Frisian")] FY,
    [Description("Xhosa")] XH,
    [Description("Yiddish")] YI, JI,
    [Description("Yoruba")] YO,
    [Description("Zhuang, Chuang")] ZA,
    [Description("Zulu")] ZU,
  }

}