<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Application">
    <Product>Microsoft.EntityFrameworkCore DB2iSeries Extensions</Product>
    <VersionPart1>10</VersionPart1>
  </PropertyGroup>
  <ItemGroup Label="PackageReferences">
    <PackageReference Include="IBM.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="System.Data.Odbc" />
  </ItemGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="xMicrosoft.EntityFrameworkCore.DB2iSeries.Tests" />
  </ItemGroup>

</Project>