<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>X10sions.Playground</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore"  />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\.DotNet\Common.DotNet.csproj" />
    <ProjectReference Include="..\..\.Abstractions\X10sions.Playground.Abstractions.csproj" />
  </ItemGroup>
</Project>
