<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsShippingPackage>false</IsShippingPackage>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>X10sions.ERP.UI</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup Label="PackageReferences">
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.WindowsForms" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\.Razor\X10sions.ERP.Razor.csproj" />
  </ItemGroup>
</Project>