<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace></RootNamespace>
  </PropertyGroup>
  <ItemGroup Label="PackageReferences">
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup Label="ProjectReferences">
    <ProjectReference Include="..\xLinqToDB.DataProvider.DB2iSeries.csproj" />
    <!-- 
    <ProjectReference Include="..\..\..\..\..\..\x10sions\X10sions.git\src\Common\.Testing\.XUnit\Common.Testing.XUnit.csproj" />
    -->
  </ItemGroup>
</Project>