<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>_Console</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Testing\PuppeteerSharp.cshtml" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Testing\PuppeteerSharp.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup Label="PackageReferences">
    <PackageReference Include="PuppeteerSharp" />
  </ItemGroup>
</Project>
