using Microsoft.EntityFrameworkCore.Storage;
using System;
using System.Collections.Generic;

namespace xEFCore.xAS400.Storage.Internal {
  public class StoreTypeMappings_AS400 : Dictionary<string, RelationalTypeMapping> {

    public StoreTypeMappings_AS400() : base(StringComparer.OrdinalIgnoreCase) {
      //Add("bigint", AS400TypeMapper.BigInt);
      //Add("bigserial", AS400TypeMapper.BigInt);
      //Add("serial8", AS400TypeMapper.BigInt);
      //OK  Add("byte", AS400TypeMapper.Binary);
      //OK        Add("binary varying", AS400TypeMapper.VarBinary);
      //OK  Add("binary", AS400TypeMapper.Binary);
      //Add("rowid", AS400TypeMapper.RowId);
      //Add("bit", AS400TypeMapper.Bit);
      //Add("boolean", AS400TypeMapper.Boolean);
      //Add("char varying", AS400TypeMapper.VarChar);
      //OK  Add("char", AS400TypeMapper.Char);
      //OK  Add("character varying", AS400TypeMapper.VarChar);
      //OK  Add("character", AS400TypeMapper.Char);
      //Add("date", AS400TypeMapper.DateTime);
      //Add("datetime", AS400TypeMapper.DateTime);
      //Add("datetime2", AS400TypeMapper.DateTime);
      //Add("datetimeoffset", AS400TypeMapper.DateTimeOffset);
      //Add("interval", AS400TypeMapper.Interval);
      //Add("interval day to day", AS400TypeMapper.Interval);
      //Add("interval day to hour", AS400TypeMapper.Interval);
      //Add("interval day to minute", AS400TypeMapper.Interval);
      //Add("interval day to second", AS400TypeMapper.Interval);
      //Add("interval day to fraction", AS400TypeMapper.Interval);
      //Add("interval day(precision) to day", AS400TypeMapper.Interval);
      //Add("interval day(precision) to hour", AS400TypeMapper.Interval);
      //Add("interval day(precision) to minute", AS400TypeMapper.Interval);
      //Add("interval day(precision) to second", AS400TypeMapper.Interval);
      //Add("interval day(precision) to fraction", AS400TypeMapper.Interval);
      //Add("interval day(precision) to fraction(scale)", AS400TypeMapper.Interval);
      //Add("interval hour to hour", AS400TypeMapper.Interval);
      //Add("interval hour to minute", AS400TypeMapper.Interval);
      //Add("interval hour to second", AS400TypeMapper.Interval);
      //Add("interval hour to fraction", AS400TypeMapper.Interval);
      //Add("interval hour(precision) to hour", AS400TypeMapper.Interval);
      //Add("interval hour(precision) to minute", AS400TypeMapper.Interval);
      //Add("interval hour(precision) to second", AS400TypeMapper.Interval);
      //Add("interval hour(precision) to fraction", AS400TypeMapper.Interval);
      //Add("interval hour(precision) to fraction(scale)", AS400TypeMapper.Interval);
      //Add("interval minute to minute", AS400TypeMapper.Interval);
      //Add("interval minute to second", AS400TypeMapper.Interval);
      //Add("interval minute to fraction", AS400TypeMapper.Interval);
      //Add("interval minute(precision) to minute", AS400TypeMapper.Interval);
      //Add("interval minute(precision) to second", AS400TypeMapper.Interval);
      //Add("interval minute(precision) to fraction", AS400TypeMapper.Interval);
      //Add("interval minute(precision) to fraction(scale)", AS400TypeMapper.Interval);
      //Add("interval second to second", AS400TypeMapper.Interval);
      //Add("interval second to fraction", AS400TypeMapper.Interval);
      //Add("interval second(precision) to second", AS400TypeMapper.Interval);
      //Add("interval second(precision) to fraction", AS400TypeMapper.Interval);
      //Add("interval fraction to fraction", AS400TypeMapper.Interval);
      //Add("interval fraction to fraction(scale)", AS400TypeMapper.Interval);
      //Add("interval year to year", AS400TypeMapper.Interval);
      //Add("interval year to month", AS400TypeMapper.Interval);
      //Add("interval year(precision) to year", AS400TypeMapper.Interval);
      //Add("interval year(precision) to month", AS400TypeMapper.Interval);
      //Add("interval month to month", AS400TypeMapper.Interval);
      //Add("interval month(precision) to month", AS400TypeMapper.Interval);
      //Add("datetime year to year", AS400TypeMapper.DateTime);
      //Add("datetime year to month", AS400TypeMapper.DateTime);
      //Add("datetime year to day", AS400TypeMapper.DateTime);
      //Add("datetime year to hour", AS400TypeMapper.DateTime);
      //Add("datetime year to minute", AS400TypeMapper.DateTime);
      //Add("datetime year to second", AS400TypeMapper.DateTime);
      //Add("datetime year to fraction", AS400TypeMapper.DateTime);
      //Add("datetime year to fraction(scale)", AS400TypeMapper.DateTime);
      //Add("datetime month to month", AS400TypeMapper.DateTime);
      //Add("datetime month to day", AS400TypeMapper.DateTime);
      //Add("datetime month to hour", AS400TypeMapper.DateTime);
      //Add("datetime month to minute", AS400TypeMapper.DateTime);
      //Add("datetime month to second", AS400TypeMapper.DateTime);
      //Add("datetime month to fraction", AS400TypeMapper.DateTime);
      //Add("datetime month to fraction(scale)", AS400TypeMapper.DateTime);
      //Add("datetime day to day", AS400TypeMapper.DateTime);
      //Add("datetime day to hour", AS400TypeMapper.DateTime);
      //Add("datetime day to minute", AS400TypeMapper.DateTime);
      //Add("datetime day to second", AS400TypeMapper.DateTime);
      //Add("datetime day to fraction", AS400TypeMapper.DateTime);
      //Add("datetime day to fraction(scale)", AS400TypeMapper.DateTime);
      //Add("datetime hour to hour", AS400TypeMapper.Time);
      //Add("datetime hour to minute", AS400TypeMapper.Time);
      //Add("datetime hour to second", AS400TypeMapper.Time);
      //Add("datetime hour to fraction", AS400TypeMapper.DateTime);
      //Add("datetime hour to fraction(scale)", AS400TypeMapper.DateTime);
      //Add("datetime minute to minute", AS400TypeMapper.Time);
      //Add("datetime minute to second", AS400TypeMapper.Time);
      //Add("datetime minute to fraction", AS400TypeMapper.DateTime);
      //Add("datetime minute to fraction(scale)", AS400TypeMapper.DateTime);
      //Add("datetime second to second", AS400TypeMapper.Time);
      //Add("datetime second to fraction", AS400TypeMapper.DateTime);
      //Add("datetime second to fraction(scale)", AS400TypeMapper.DateTime);
      //Add("datetime fraction to fraction", AS400TypeMapper.DateTime);
      //Add("datetime fraction to fraction(scale)", AS400TypeMapper.DateTime);
      //Add("dec", AS400TypeMapper.Decimal);
      //Add("decimal", AS400TypeMapper.Decimal);
      //OK  Add("image", AS400TypeMapper.VarBinary);
      //Add("int", AS400TypeMapper.Int);
      //Add("int8", AS400TypeMapper.BigInt);
      //Add("serial", AS400TypeMapper.Int);
      //Add("money", AS400TypeMapper.Decimal);
      //OK  Add("national char varying", AS400TypeMapper.NVarChar);
      //OK  Add("national character varying", AS400TypeMapper.NVarChar);
      //OK  Add("national character", AS400TypeMapper.NChar);
      //OK  Add("nchar", AS400TypeMapper.NChar);
      //OK  Add("ntext", AS400TypeMapper.NVarChar);
      //Add("numeric", AS400TypeMapper.Decimal);
      //OK  Add("nvarchar", AS400TypeMapper.NVarChar);
      //Add("real", AS400TypeMapper.Real);
      //OK  Add("rowversion", AS400TypeMapper.RowVersion);
      //Add("smalldatetime", AS400TypeMapper.DateTime);
      //Add("smallint", AS400TypeMapper.SmallInt);
      //Add("smallmoney", AS400TypeMapper.Decimal);
      //OK  Add("text", AS400TypeMapper.VarChar);
      //Add("time", AS400TypeMapper.Time);
      //Add("timestamp", AS400TypeMapper.DateTime);
      //Add("tinyint", AS400TypeMapper.Byte);
      //Add("uniqueidentifier", AS400TypeMapper.UniqueIdentifier);
      //OK  Add("varbinary", AS400TypeMapper.VarBinary);
      //OK  Add("varchar", AS400TypeMapper.VarChar);
      //OK  Add("lvarchar", AS400TypeMapper.VarChar);
      //Add("xml", AS400TypeMapper.Xml);
      //Add("integer", AS400TypeMapper.Int);
      //Add("timestamp(max) with time zone", AS400TypeMapper.TimeStampMax);
      //Add("timestamp(max) without time zone", AS400TypeMapper.TimeStampMax);
      //Add("blob", AS400TypeMapper.Blob);
      //Add("clob", AS400TypeMapper.Clob);
      //Add("float", AS400TypeMapper.Double);
      //Add("double", AS400TypeMapper.Double);
      //Add("decfloat", AS400TypeMapper.DecFloat);
      //Add("dbclob", AS400TypeMapper.DbClob);
      //Add("char for bit data", AS400TypeMapper.CharForBitData);
      //Add("character for bit data", AS400TypeMapper.CharacterForBitData);
      //Add("varchar for bit data", AS400TypeMapper.VarCharForBitData);
      //Add("graphic", AS400TypeMapper.Graphic);
      //Add("vargraphic", AS400TypeMapper.VarGraphic);
      //Add("varg", AS400TypeMapper.VarG);
      //Add("varbin", AS400TypeMapper.VarBin);
      //Add("timestz", AS400TypeMapper.TimeStz);
      //Add("timestmp", AS400TypeMapper.TimeStmp);
      //Add("longvarg", AS400TypeMapper.LongVarG);
      //Add("longvar", AS400TypeMapper.LongVar);
      //Add("_datalink", AS400TypeMapper.DataLink);
    }

  }
}