<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>X10sions.Wsus</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" >
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design"  />
  </ItemGroup>
  <ItemGroup Label="ProjectReferences">
    <ProjectReference Include="..\X10sions.Wsus.csproj" />
  </ItemGroup>
</Project>
