<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Application">
    <TargetFramework>netstandard2.0</TargetFramework>
    <Product>Common NetStandard</Product>
    <RootNamespace>Common</RootNamespace>
    <VersionPart1>2</VersionPart1>
    <VersionPart2>0</VersionPart2>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Models\DateOnly.cs" />
    <Compile Remove="Models\DateTimeOnly.cs" />
    <Compile Remove="Models\TimeOnly.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.TimeProvider" />
    <PackageReference Include="Portable.System.DateTimeOnly" />
    <PackageReference Include="System.ComponentModel.Annotations" />
    <PackageReference Include="System.Memory" />
  </ItemGroup>
  <ItemGroup Label="PackageReferences">
    <PackageReference Update="FastExpressionCompiler.LightExpression" />
  </ItemGroup>
  <ItemGroup Label="ProjectReferences">
    <ProjectReference Include="..\..\x\xSystem\.DotNetStandard\xSystem.DotNetStandard.csproj" />
  </ItemGroup>
</Project>