<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>X10sions.Playground</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\.Fake\.Domain\X10sions.Fake.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="App\" />
  </ItemGroup>
</Project>
